---
name: Build & Push Docker Image

# Only builds the image if a release was created.
# This guarantees the commit is tagged and on main branch.
# (see https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)

# yamllint disable-line rule:truthy
on:
  release:

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/docker_dockerhub_release_callable.yml@733afe1105fc85fafc25cddbc3c34b48c2c3d6fa
    secrets: inherit
    with:
      # TODO insert DockerHub repository name from our organization: https://hub.docker.com/u/hlag
      # type: string
      # required: true
      # description: Name of the image. Usually it is sensible to set this to the repository name
      image-name: "name-of-the-dockerhub-repository"
      # TODO should always be set to true and can be removed here
      # type: boolean
      # required: false
      # description: Flag to enable the workflow to actually push the built image to the registry
      push: "true"
      # TODO security scanning is important and should always be set to true (default) and removed here
      # type: boolean
      # required: false
      # description: Upload results of trivy scan of docker image to Github Security page
      upload-security-scan-results: "true"
