---
name: Build & Push Docker Image

# Only builds the image if a release was created.
# This guarantees the commit is tagged and on main branch.
# (see https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)

# yamllint disable-line rule:truthy
on:
  # don't run this workflow initially. we have an init-branch to fix that
  workflow_dispatch:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/dockerhub_release.yml@23fe0e49858d501e89bc26f0408c2b6b3b408d55 # 1.21.3
    secrets: inherit
