---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    # using a GitHub only release here. Use .github/update_workflows.sh to switch to a Docker release
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_release_callable.yml@e8c1c3deb93315b82c4bcd4957b215fd5f94e1c2
    secrets: inherit
